### ISSUE TITLE
dailyclean-api demo crash on startup

### ISSUE THREAD

**Issue by guillaume-chervet** [AxaGuilDEv/dailyclean#51]
hi @guillaume-thomas, 

It seems dailyclean-api demo crash on startup,

![image](https://user-images.githubusercontent.com/52236059/186095570-e3922442-da03-4c72-8de7-bd033215586b.png)

Log display that:
`
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-08-23 07:16:00,675 INFO  [fr.axa.ope.dai.res.TimeRangesResource] (main) The application is starting, we have to update cronJobs...
2022-08-23 07:16:00,676 WARN  [io.fab.kub.cli.int.VersionUsageUtils] (main) The client is using resource type 'cronjobs' with unstable version 'v1beta1'
2022-08-23 07:16:00,879 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/batch/v1beta1/namespaces/license-preproduction/cronjobs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. cronjobs.batch is forbidden: User "system:serviceaccount:license-preproduction:default" cannot list resource "cronjobs" in API group "batch" in the namespace "license-preproduction".
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:583)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:520)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:487)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:448)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:431)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:161)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:664)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:86)
        at fr.axa.openpaas.dailyclean.service.KubernetesService.getCronJob(KubernetesService.java:145)
        at fr.axa.openpaas.dailyclean.service.KubernetesService.updatingCronJobIfNeeded(KubernetesService.java:120)
        at fr.axa.openpaas.dailyclean.service.KubernetesService_ClientProxy.updatingCronJobIfNeeded(KubernetesService_ClientProxy.zig:273)
        at fr.axa.openpaas.dailyclean.resource.TimeRangesResource.onStart(TimeRangesResource.java:57)
        at fr.axa.openpaas.dailyclean.resource.TimeRangesResource_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(TimeRangesResource_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:147)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:565)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
`

**Comment by guillaume-chervet** [comment]
done by #52
